<?php

namespace Votee\Bundle\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoiceRepository extends EntityRepository
{
}
